blank_issues_enabled: true
contact_links:
  - name: focus extension support
    url: https://github.com/ChunhThanhDe/focus/issues/20#issuecomment-new
    about: Please ask and answer off-topic questions here.
