blank_issues_enabled: true
contact_links:
  - name: Focus Extension Support
    url: https://github.com/ChunhThanhDe/focus/issues/1#issuecomment-new
    about: Please ask and answer off-topic questions here.
